template: 'facelessuser:master-labels:labels.yml:master'

# Wildcard labels

brace_expansion: true
extended_glob: true

rules:
  - labels: [infrastructure]
    patterns: ['*|@(requirements|.github)/**|-*.md']

  - labels: [source]
    patterns: ['pyspelling/**']

  - labels: [docs]
    patterns: ['*.md|docs/**']

  - labels: [tests]
    patterns: ['tests/**']

  - labels: [plugins]
    patterns: ['pyspelling/@(filters|flow_control)/**|pyspelling/plugin.py']

  - labels: [wildcard-flow-control]
    patterns: ['@(tests|pyspelling)/**/?(test_)wildcard.py']

  - labels: [context-filter]
    patterns: ['@(tests|pyspelling)/**/?(test_)context.py']

  - labels: [cpp-filter]
    patterns: ['@(tests|pyspelling)/**/?(test_)cpp.py']

  - labels: [html-filter]
    patterns: ['@(tests|pyspelling)/**/?(test_)html.py']

  - labels: [javascript-filter]
    patterns: ['@(tests|pyspelling)/**/?(test_)javascript.py']

  - labels: [markdown-filter]
    patterns: ['@(tests|pyspelling)/**/?(test_)markdown.py']

  - labels: [odf-filter]
    patterns: ['@(tests|pyspelling)/**/?(test_)odf.py']

  - labels: [ooxml-filter]
    patterns: ['@(tests|pyspelling)/**/?(test_)ooxml.py']

  - labels: [python-filter]
    patterns: ['@(tests|pyspelling)/**/?(test_)python.py']

  - labels: [stylesheets-filter]
    patterns: ['@(tests|pyspelling)/**/?(test_)stylesheets.py']

  - labels: [text-filter]
    patterns: ['@(tests|pyspelling)/**/?(test_)text.py']

  - labels: [url-filter]
    patterns: ['@(tests|pyspelling)/**/?(test_)url.py']

  - labels: [xml-filter]
    patterns: ['@(tests|pyspelling)/**/?(test_)xml.py']

# Label management

labels:
- name: plugins
  color: subcategory
  description: Related to general plugin code.

- name: wildcard-flow-control
  color: pending
  description: Wildcard flow control.

- name: context-filter
  color: subcategory
  description: Related to the context filter.

- name: cpp-filter
  color: subcategory
  description: Related to the cpp filter.

- name: html-filter
  color: subcategory
  description: Related to the html filter.

- name: javascript-filter
  color: subcategory
  description: Related to the javascript filter.

- name: markdown-filter
  color: subcategory
  description: Related to the markdown filter.

- name: odf-filter
  color: subcategory
  description: Related to the odf filter.

- name: ooxml-filter
  color: subcategory
  description: Related to the ooxml filter.

- name: python-filter
  color: subcategory
  description: Related to the python filter.

- name: stylesheets-filter
  color: subcategory
  description: Related to the stylesheets filter.

- name: text-filter
  color: subcategory
  description: Related to the text filter.

- name: url-filter
  color: subcategory
  description: Related to the url filter.

- name: xml-filter
  color: subcategory
  description: Related to the xml filter.
