documents:
- name: mkdocs
  sources:
    - site
  aspell:
    lang: en
  dictionary:
    lang: en
    wordlists:
      - docs/src/dictionary/en-custom.txt
    output: build/dictionary/mkdocs.dic
  filters:
    - pyspelling.parsers.html_parser:
        comments: false
        attributes:
          - title
          - alt
        ignores:
          - code
          - pre
          - a.magiclink-compare
          - a.magiclink-commit
          - span.keys
          - .MathJax_Preview
          - .md-nav__link
          - .md-footer-custom-text
          - .md-source__repository
          - .headerlink
          - .md-icon

- name: markdown
  sources:
    - README.md
  aspell:
    lang: en
  dictionary:
    lang: en
    wordlists:
      - docs/src/dictionary/en-custom.txt
    output: build/dictionary/mkdocs.dic
  filters:
    - pyspelling.parsers.markdown_parser:
    - pyspelling.parsers.html_parser:
        comments: false
        attributes:
          - title
          - alt
        ignores:
          - code
          - pre

- name: python
  sources:
    - setup.py
    - pyspelling
  aspell:
    lang: en
  dictionary:
    lang: en
    wordlists:
      - docs/src/dictionary/en-custom.txt
    output: build/dictionary/python.dic
  filters:
    - pyspelling.parsers.python_parser:
        strings: false
        comments: false
    - pyspelling.parsers.context_parser:
        context_visible_first: true
        escapes: \\[\\`~]
        delimiters:
          - open: (?P<open>`+)
            content: .*?
            close: (?P=open)
          - open: (?s)^(?P<open>\s*~{3,})
            content: .*?
            close: ^(?P=open)$
