language: python
dist: xenial
sudo: true

# Limit git depth to speed up build
git:
  depth: 5

matrix:
  include:
  - python: 3.5
    env:
    - TOXENV=py35
    - TOX_SPELL_REQUIRE=aspell
  - python: 3.6
    env:
    - TOXENV=py36
    - TOX_SPELL_REQUIRE=aspell
  - python: 3.7
    env:
    - TOXENV=py37
    - TOX_SPELL_REQUIRE=aspell
  - python: 3.8-dev
    env:
    - TOXENV=py38
    - TOX_SPELL_REQUIRE=aspell

install:
- pip install tox
- pip install codecov

script:
- tox

after_success:
- codecov
