build: false

clone_depth: 5

environment:
  matrix:
    - PYTHON: "C:/Python34"
      TOXENV: "py34"
    - PYTHON: "C:/Python35"
      TOXENV: "py35"
    - PYTHON: "C:/Python36"
      TOXENV: "py36"
    - PYTHON: "C:/Python37"
      TOXENV: "py37"
    - PYTHON: "C:/Python36"
      TOXENV: "lint"

init:
  - "ECHO %TOXENV%"
  - "ECHO %PYTHON%"
  - ps: "ls C:/Python*"

install:
  - curl -fsS -o hunspell.zip https://github.com/facelessuser/hunspell-windows/releases/download/2.1/hunspell-windows-h-1.6.2-1-d-9ec31e4-v2.zip
  - 7z x hunspell.zip -ohunspell
  - "%PYTHON%/Scripts/pip.exe install virtualenv"
  - "%PYTHON%/Scripts/pip.exe install tox"
  - "%PYTHON%/Scripts/pip.exe install codecov"
  - "SET PATH=%CD%\\hunspell\\bin;%PYTHON%;%PYTHON%\\Scripts;%PATH%"

test_script:
  - pip --version
  - virtualenv --version
  - tox --version
  - tox

after_test:
  - if not ("%TOXENV%" == "lint") codecov

matrix:
  fast_finish: true
